extends:
  - stylelint-config-standard
  - stylelint-config-prettier
rules:
  alpha-value-notation: number
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - /^custom-(media|selector)/
  declaration-no-important: true
  font-weight-notation: named-where-possible
  max-nesting-depth: 2
  no-descending-specificity: null
  time-min-milliseconds: 100
