strict_front_matter: true
timezone: America/Detroit

repository: mgsisk/mgsisk.github.io

theme: null
title: Michael Sisk
url: https://mgsisk.com
baseurl: /

exclude:
  - CODEOWNERS
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - node_modules
  - package-lock.json
  - package.json
  - Vagrantfile
