title: Michael Sisk
description: >
  I'm a designer, developer, and creator from Michigan with a passion for the
  web, awful movies, and setting people on fire.
url: https://mgsisk.com
defaults:
  - scope:
      path: ''
    values:
      image: hero-small.jpg
      aside: complementary.md
include:
  - _pages
exclude:
  - Brewfile
  - Gemfile
  - Gemfile.lock
  - license.md
  - node_modules
  - package-lock.json
  - package.json
  - readme.md
  - scripts.js
